### PR TITLE
Add host-vdiskmap as gather_subset options

### PR DESCRIPTION
**Pull request by orbist**
Requires an objectname, so only added as gather_subset options, not included in "all"

##### SUMMARY
Adds two new options to gather_subset to run lshostvdiskmap and lsvdiskhostmap

##### ISSUE TYPE
New feature

### CODE REVIEW

**Comment by Shilpi-J** [comment]
The changes are having sanity errors.

**Comment by orbist** [comment]
Fixed up sanity errors, please check its happy now :)

**Comment by orbist** [comment]
Everything looks ok, there are two commits, the second one fixes the sanity errors and the file at  :  https://github.com/orbist/ibm.spectrum_virtualize/blob/develop/plugins/modules/ibm_svc_info.py is the latest.

**Review by Shilpi-J — CHANGES_REQUESTED** [review]
Please fix sanity errors.

**Review by Shilpi-J — APPROVED** [review]

**Pull request merged**
